### ISSUE TITLE
Web push notifications

### ISSUE THREAD

**Issue by ZalgirisKaunas** [f3oall/awesome-notifications#19]
It would be really amazing if you had an option to generate web push notifications.

Do you plan to support that in the future?

**Comment by andreasvirkus** [comment]
I think you mean just notifications (pop-ups) via the [Notification API](https://developer.mozilla.org/en-US/docs/Web/API/notification)? The Web [Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API) is something different and requires server-side logic (they're often mixed up since they're used together so often that people just refer to the whole setup as "Push Notifications" - although it's 2 different APIs)

**Comment by f3oall** [comment]
Hey @ZalgirisKaunas , 

No I don't have a plan to support it inside this library. Web push notifications are pretty far from purposes of awesome-notifications.
